apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-master
  template:
    metadata:
      labels:
        app: discovery-master
    spec:
      containers:
      - name: discovery-master
        image: gcr.io/castroom/discovery-master:v3
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: AWS_DISCOVERY_MASTER_ACCESS_KEY_ID
            value: "AKIAXHBB3XTHAX6CUTMJ"
          - name: AWS_DISCOVERY_MASTER_SECRET_ACCESS_KEY
            value: "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"
