apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-crawler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-crawler
  template:
    metadata:
      labels:
        app: discovery-crawler
    spec:
      containers:
      - name: discovery-crawler
        image: gcr.io/castroom/discovery-crawler:v5
        imagePullPolicy: "Always"
        env:
          - name: AWS_DISCOVERY_CRAWLER_ACCESS_KEY_ID
            value: ""
          - name: AWS_DISCOVERY_CRAWLER_SECRET_ACCESS_KEY
            value: ""
          - name: SQS_URL
            value: ""
          - name: MASTER_NODE_URL
            value: ""
          - name: ELASTICSEARCH_URL
            value: ""
        
